events {}
http {
    upstream backend {
        # Nginx będzie wysyłał ruch do usługi "api" na port 8080
        server api:8080;
    }
    server {
        listen 80;
        location / {
            proxy_pass http://backend;
        }
    }
}